### ISSUE TITLE
Is MultiChunkedEncoding enabled?

### ISSUE THREAD

**Issue by skyfranky** [async-aws/aws#1005] opened 2021-05-15 04:19 UTC
Hi

My site is using this library for S3 and want to extend the support for  an inter-operable with the AWS S3 API Alibaba Cloud OSS. 
https://www.alibabacloud.com/help/doc-detail/64919.htm

somehow I got ErrorMsg: Aws MultiChunkedEncoding is not supported. 
My endpoint use https, and it should be able disable MultiChunkedEncoding but not working.

QUESTION:
Do you enforce any MultiChunkedEncoding in this library? any way that can disable it?

**Comment by jderusse** [comment] 2021-05-15 08:00
this can be disabled with `sendChunkedBody`

https://async-aws.com/clients/s3.html#chunked-body

**Comment by skyfranky** [comment] 2021-05-15 09:03
thanks for the quick reply, and the error gone after disable it. now I can upload image successfully to my bucket via this library. 

somehow there is one problem that the uploaded folder path is wrong. this is the uploaded image url:
https://mc-dir-photo.oss-cn-hongkong.aliyuncs.com/mc-dir-photo/original/fb/2d/2e/white-cloud-blue-sky-sea-74190-4488-77-1621069091.jpg

I can see the library created a folder using the bucket name "mc-dir-photo", the correct upload path should be:
https://mc-dir-photo.oss-cn-hongkong.aliyuncs.com/original/fb/2d/2e/white-cloud-blue-sky-sea-74190-4488-77-1621069091.jpg


QUESTION:
what code is causing the upload to create a folder using bucket name? hope you can give me a direction to troubleshoot this, thank you very much :)

below is my codes for endpoint, which contains the bucketname + endpoint 


`$this->spaces = new SimpleS3Client([
				'accessKeyId' => $this->getKey(),
				'accessKeySecret' => $this->getSecret(),
				'region' => $this->getRegion(),
	            'endpoint' => 'https://' . $this->getBucket() . '.' . $this->getEndpoint(),
				'pathStyleEndpoint' => true,
				'sendChunkedBody' => false,				
			]);
`

**Comment by jderusse** [comment] 2021-05-15 09:07
Try disabling `pathStyleEndpoint` maybe it confuses AlibabaCloud

**Comment by skyfranky** [comment] 2021-05-15 10:13
upload fails and got error 500 if set 'pathStyleEndpoint' => false,

`$this->spaces = new SimpleS3Client([
				'accessKeyId' => $this->getKey(),
				'accessKeySecret' => $this->getSecret(),
				'region' => $this->getRegion(),
	            'endpoint' => 'https://' . $this->getBucket() . '.' . $this->getEndpoint(),
				'pathStyleEndpoint' => false,
				'sendChunkedBody' => false,				
			]);`

**Comment by Nyholm** [comment] 2021-05-21 12:18
Awesome. I'll close this issue since it looks like the problem is resolved.

**Closed by Nyholm** 2021-05-21 12:18 UTC
